"""
item_overrides.py
-----------------
Manual category overrides for specific item IDs.
These corrections apply to BOTH the Excel/PDF output (cat label)
AND the web app JSON (category field drives TAXONOMY lookup).
"""

# Initialize the dictionary first so Python knows it exists
ITEM_CATEGORY_OVERRIDES = {}

# Now you can safely update it with your mappings
ITEM_CATEGORY_OVERRIDES.update({

    # ── Irons ──
    "76133": {"parent": "Home & Office", "sub": "Irons"},
    "76134": {"parent": "Home & Office", "sub": "Irons"},
    "IM-36CR": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-42BK": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-59BK": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-59R": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-59W": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-51BK": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-51W": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-69BKRG": {"parent": "Home & Office", "sub": "Irons"},
    "MPI-70": {"parent": "Home & Office", "sub": "Irons"},
    "14210R": {"parent": "Home & Office", "sub": "Irons"},

    # ── Calculators ──
    "CA656": {"parent": "Home & Office", "sub": "Calculators"},
    "CA700": {"parent": "Home & Office", "sub": "Calculators"},
    "CALCA275": {"parent": "Home & Office", "sub": "Calculators"},
    "CR-35": {"parent": "Home & Office", "sub": "Alarm Clocks"},
    "CR1860D": {"parent": "Home & Office", "sub": "Alarm Clocks"},
    "CR640D": {"parent": "Home & Office", "sub": "Alarm Clocks"},
    "HPXSPBT14": {"parent": "Home & Office", "sub": "Alarm Clocks"},
    "HPXSPBT18": {"parent": "Home & Office", "sub": "Alarm Clocks"},
    "RC551": {"parent": "Home & Office", "sub": "Alarm Clocks"},
    "WAC5-1002-BLK": {"parent": "Home & Office", "sub": "Alarm Clocks"},

    # ── Vacuums ──
    "BDSV53-BLK": {"parent": "Home & Office", "sub": "Vacuums"},
    "NEU102/RBO": {"parent": "Home & Office", "sub": "Vacuums"},
    "NEU180": {"parent": "Home & Office", "sub": "Vacuums"},
    "NEU203/RBO": {"parent": "Home & Office", "sub": "Vacuums"},
    "NV-09163": {"parent": "Home & Office", "sub": "Vacuums"},
    "VC-450-BLU": {"parent": "Home & Office", "sub": "Vacuums"},
    "VC-450-GRN": {"parent": "Home & Office", "sub": "Vacuums"},
    "VC-450-YLW": {"parent": "Home & Office", "sub": "Vacuums"},
    "VC-459-WHT": {"parent": "Home & Office", "sub": "Vacuums"},
    "STM-4000BK": {"parent": "Home & Office", "sub": "Vacuums"},

    # ── TV Wall Mounts ──
    "BKS-720-315": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "BKS-720-369": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "BKS-720-855": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "BKS-720-891": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "RM-720-9128": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "RM-918-8108": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-513-904": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-513-972": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-3026": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-3063": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-6030": {"parent": "Home & Office", "sub": "TV Stands"},
    "SM-720-8079": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-8318A": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-8532": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-8550": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-8712": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-8730": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-8904C": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-720-8910": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "SM-918-3016": {"parent": "Home & Office", "sub": "TV Wall Mounts"},
    "TV1000-RTA": {"parent": "Home & Office", "sub": "TV Stands"},
    "TV3BS-A": {"parent": "Home & Office", "sub": "TV Stands"},
    "TV700": {"parent": "Home & Office", "sub": "TV Stands"},

    # ── Electronics & Accessories ──
    "AH100R": {"parent": "Electronics", "sub": "Cables"},
    "DV10R": {"parent": "Electronics", "sub": "Cables"},
    "VH25HHR": {"parent": "Electronics", "sub": "Cables"},
    "VH26HHR": {"parent": "Electronics", "sub": "Cables"},
    "VH50HHR": {"parent": "Electronics", "sub": "Cables"},
    "RCU300TZ": {"parent": "Electronics", "sub": "Remotes"},
    "RCR414BHE1": {"parent": "Electronics", "sub": "Remotes"},
    "REM-11": {"parent": "Electronics", "sub": "Remotes"},
    "REM-6": {"parent": "Electronics", "sub": "Remotes"},
    "SRP4221B/27": {"parent": "Electronics", "sub": "Remotes"},
    "TKTC6GB": {"parent": "Electronics", "sub": "Remotes"},
    "RCR504BE": {"parent": "Electronics", "sub": "Remotes"},
    "REM-13-BLK": {"parent": "Electronics", "sub": "Remotes"},
    "REM-13-SIL": {"parent": "Electronics", "sub": "Remotes"},
    "SRP2024R-27": {"parent": "Electronics", "sub": "Remotes"},
    "ANT-100": {"parent": "Electronics", "sub": "Antennas"},
    "ANTD4E": {"parent": "Electronics", "sub": "Antennas"},
    "ANT1560E": {"parent": "Electronics", "sub": "Antennas"},
    "ANT310E": {"parent": "Electronics", "sub": "Antennas"},
    "ANT-101": {"parent": "Electronics", "sub": "Antennas"},
    "ANT-22": {"parent": "Electronics", "sub": "Antennas"},
    "ANT-400": {"parent": "Electronics", "sub": "Antennas"},
    "ANT-7-BLK": {"parent": "Electronics", "sub": "Antennas"},
    "ANT1080E": {"parent": "Electronics", "sub": "Antennas"},
    "ANT111E": {"parent": "Electronics", "sub": "Antennas"},
    "ANT111E/RB": {"parent": "Electronics", "sub": "Antennas"},
    "ANT121E/RB": {"parent": "Electronics", "sub": "Antennas"},
    "ANT30MILE": {"parent": "Electronics", "sub": "Antennas"},
    "ANT751Z": {"parent": "Electronics", "sub": "Antennas"},
    "AZONJN9": {"parent": "Electronics", "sub": "Antennas"},
    "FX-181": {"parent": "Electronics", "sub": "Car Audio"},
    "NA-3032": {"parent": "Electronics", "sub": "Car Audio"},
    "FMT-13": {"parent": "Electronics", "sub": "Car Audio"},
    "FX-911": {"parent": "Electronics", "sub": "Car Audio"},

    # ── Power ──
    "ADP-101": {"parent": "Electronics", "sub": "Chargers"},
    "WPF4-1008-RED": {"parent": "Electronics", "sub": "Power Banks"},
    "SA150": {"parent": "Electronics", "sub": "Timers"},
    "SA230": {"parent": "Electronics", "sub": "Timers"},
    "SA215": {"parent": "Electronics", "sub": "Timers"},
    "SA315": {"parent": "Electronics", "sub": "Timers"},
    "37210": {"parent": "Electronics", "sub": "Surge Protectors"},

    # ── Power Banks ──
    "FWPB502K": {"parent": "Electronics", "sub": "Power Banks"},
    "FWPB515K": {"parent": "Electronics", "sub": "Power Banks"},
    "FWPB515W": {"parent": "Electronics", "sub": "Power Banks"},
    "PTB-1010": {"parent": "Electronics", "sub": "Power Banks"},
    "PTB-1520": {"parent": "Electronics", "sub": "Power Banks"},
    "VPUR1011-WHT-ST": {"parent": "Electronics", "sub": "Power Banks"},
    "HPXKX525": {"parent": "Electronics", "sub": "Computing"},
    "HPXKX550": {"parent": "Electronics", "sub": "Computing"},
    "HPXKX700": {"parent": "Electronics", "sub": "Computing"},
    "D-09/CA57BN": {"parent": "Electronics", "sub": "Computing"},
    "SC-5000VD": {"parent": "Electronics", "sub": "Cameras"},
    "IP-100": {"parent": "Electronics", "sub": "Cameras"},
    "IP-365": {"parent": "Electronics", "sub": "Cameras"},
    "CS5119": {"parent": "Electronics", "sub": "Phones"},
    "CS5129": {"parent": "Electronics", "sub": "Phones"},
    "CS5129-2": {"parent": "Electronics", "sub": "Phones"},
    "SM-720-1610": {"parent": "Electronics", "sub": "Lighting"},
    "SM-720-1638": {"parent": "Electronics", "sub": "Lighting"},
    "SM-720-2000": {"parent": "Electronics", "sub": "Lighting"},
    "SM-720-2500": {"parent": "Electronics", "sub": "Lighting"},
    "SM-720-3000": {"parent": "Electronics", "sub": "Lighting"},
    "SM-720-5000": {"parent": "Electronics", "sub": "Lighting"},
    "SM-720-7500": {"parent": "Electronics", "sub": "Lighting"},
    "LSL110": {"parent": "Electronics", "sub": "Lighting"},
    "HPAMP610": {"parent": "Electronics", "sub": "Phones"},
    "HPAMP750": {"parent": "Electronics", "sub": "Chargers"},
    "FPB1200W": {"parent": "Electronics", "sub": "Power Banks"},
    "CJR720BLHD": {"parent": "Electronics", "sub": "Projectors"},
    "MHV1-1026-GRN": {"parent": "Electronics", "sub": "Cables"},
    "MHV1-1026-PUR": {"parent": "Electronics", "sub": "Cables"},

    # ── Fans, AC & Dehumidifiers ──
    "BCF5211": {"parent": "Climate Control", "sub": "Fans"},
    "WPF4-1008-WHT": {"parent": "Climate Control", "sub": "Fans"},
    "BCF5252R": {"parent": "Climate Control", "sub": "Fans"},
    "BFB09W": {"parent": "Climate Control", "sub": "Fans"},
    "F-20CRC": {"parent": "Climate Control", "sub": "Fans"},
    "F-20SW": {"parent": "Climate Control", "sub": "Fans"},
    "BD22MWSA": {"parent": "Climate Control", "sub": "Dehumidifiers"},
    "BDT50WTB": {"parent": "Climate Control", "sub": "Dehumidifiers"},
    "BFTU107": {"parent": "Climate Control", "sub": "Fans"},
    "BHD406W": {"parent": "Climate Control", "sub": "Fans"},
    "DH5023KP": {"parent": "Climate Control", "sub": "Dehumidifiers"},
    "F-16SMB": {"parent": "Climate Control", "sub": "Fans"},
    "F-16SMW": {"parent": "Climate Control", "sub": "Fans"},
    "F-16SPW": {"parent": "Climate Control", "sub": "Fans"},
    "F-1831B": {"parent": "Climate Control", "sub": "Fans"},
    "FAN-106-BLK": {"parent": "Climate Control", "sub": "Fans"},
    "FAN-106-PNK": {"parent": "Climate Control", "sub": "Fans"},
    "FAN-106-WHT": {"parent": "Climate Control", "sub": "Fans"},
    "FB-05-WHT": {"parent": "Climate Control", "sub": "Fans"},
    "FB-06-BLK": {"parent": "Climate Control", "sub": "Fans"},
    "FB-06-WHT": {"parent": "Climate Control", "sub": "Fans"},
    "FB-82-WHT": {"parent": "Climate Control", "sub": "Fans"},
    "FB-83-BLK": {"parent": "Climate Control", "sub": "Fans"},
    "FB-83-WHT": {"parent": "Climate Control", "sub": "Fans"},
    "FB-84-WHT": {"parent": "Climate Control", "sub": "Fans"},
    "FS45-9L": {"parent": "Climate Control", "sub": "Fans"},
    "MAD22S1WWT": {"parent": "Climate Control", "sub": "Dehumidifiers"},
    "PFS40A4BBB": {"parent": "Climate Control", "sub": "Fans"},
    "V/2270": {"parent": "Climate Control", "sub": "Fans"},
    "V/2271": {"parent": "Climate Control", "sub": "Fans"},
    "V/2273": {"parent": "Climate Control", "sub": "Fans"},
    "V/2274": {"parent": "Climate Control", "sub": "Fans"},
    "V/2500": {"parent": "Climate Control", "sub": "Fans"},
    "V/2742": {"parent": "Climate Control", "sub": "Fans"},
    "V/3193": {"parent": "Climate Control", "sub": "Fans"},
    "V/3488": {"parent": "Climate Control", "sub": "Fans"},
    "V/6036": {"parent": "Climate Control", "sub": "Fans"},
    "250F400W": {"parent": "Climate Control", "sub": "Fans"},
    "MSWMT24JR/RBO": {"parent": "Climate Control", "sub": "Fans"},
    "MSWMT24MB/RBO": {"parent": "Climate Control", "sub": "Fans"},
    "MSWMT24MW/RBO": {"parent": "Climate Control", "sub": "Fans"},
    "V/6829": {"parent": "Climate Control", "sub": "Fans"},
    "WLF4-1001-VAW": {"parent": "Climate Control", "sub": "Fans"},
    "FFRA051WAE": {"parent": "Climate Control", "sub": "Window AC"},
    "ETTW08E": {"parent": "Climate Control", "sub": "Window AC"},
    "ETTW10E": {"parent": "Climate Control", "sub": "Window AC"},
    "AW0823CW1W": {"parent": "Climate Control", "sub": "Window AC"},
    "AW1823TW3W": {"parent": "Climate Control", "sub": "Window AC"},
    "AWAS05BWF": {"parent": "Climate Control", "sub": "Window AC"},
    "AWCS08WWF": {"parent": "Climate Control", "sub": "Window AC"},
    "DL12AWCW": {"parent": "Climate Control", "sub": "Window AC"},
    "EWR05E": {"parent": "Climate Control", "sub": "Window AC"},
    "EWR06E": {"parent": "Climate Control", "sub": "Window AC"},
    "EWR08E": {"parent": "Climate Control", "sub": "Window AC"},
    "LW5024": {"parent": "Climate Control", "sub": "Window AC"},
    "MAW08AV1QWT-C": {"parent": "Climate Control", "sub": "Window AC"},
    "MAW08S1VWT-A": {"parent": "Climate Control", "sub": "Window AC"},
    "RAC-WK0612CRRU/ROA": {"parent": "Climate Control", "sub": "Window AC"},
    "WAW0525CM1W": {"parent": "Climate Control", "sub": "Window AC"},
    "WC05R25A": {"parent": "Climate Control", "sub": "Window AC"},
    "WC06R25A": {"parent": "Climate Control", "sub": "Window AC"},
    "WC08W25A": {"parent": "Climate Control", "sub": "Window AC"},
    "WCH08R25A": {"parent": "Climate Control", "sub": "Window AC"},
    "ARC-101CW": {"parent": "Climate Control", "sub": "Portable AC"},
    "HAP0824TWD - No Accessories": {"parent": "Climate Control", "sub": "Portable AC"},
    "MAP05S1AWT": {"parent": "Climate Control", "sub": "Portable AC"},
    "NS-AC08PWH1/ROA": {"parent": "Climate Control", "sub": "Portable AC"},
    "PX0811CWRU/ROA": {"parent": "Climate Control", "sub": "Portable AC"},
    "S-15051": {"parent": "Climate Control", "sub": "Portable AC"},
    "S-4532": {"parent": "Climate Control", "sub": "Portable AC"},
    "VAP05R1AWT/RB": {"parent": "Climate Control", "sub": "Portable AC"},
    "VAP09R1AWT/RB": {"parent": "Climate Control", "sub": "Portable AC"},
    "VAP09R1AWT/ROA": {"parent": "Climate Control", "sub": "Portable AC"},
    "VPMS05BWT": {"parent": "Climate Control", "sub": "Portable AC"},
    "LW1017ERSM1": {"parent": "Climate Control", "sub": "Window AC"},
    "FFRE1533U10/ROA": {"parent": "Climate Control", "sub": "Window AC"},
    "MAW12V1YWT-S": {"parent": "Climate Control", "sub": "Window AC"},
    "BAB-2438/ROA": {"parent": "Climate Control", "sub": "Accessories"},
    "TSB-2438/ROA": {"parent": "Climate Control", "sub": "Accessories"},
    "HAP9435B": {"parent": "Climate Control", "sub": "Air Purifiers"},

    # ── Heaters ──
    "BHOC05": {"parent": "Climate Control", "sub": "Heaters"},
    "NT15-20A/G": {"parent": "Climate Control", "sub": "Heaters"},
    "CZ550": {"parent": "Climate Control", "sub": "Heaters"},
    "HO-0250H": {"parent": "Climate Control", "sub": "Heaters"},
    "RSWW1": {"parent": "Climate Control", "sub": "Heaters"},
    "WHT3001": {"parent": "Climate Control", "sub": "Heaters"},
    "BHF136193153/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "BHOC05/ROA": {"parent": "Climate Control", "sub": "Heaters"},
    "HCX9115E/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "MSH20Q3ABB/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "MSH20Q3AWW/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "PSH08F1ABB/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "PSH08F1AWW/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "PSH20Q3ABB/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "WSH0702ABB/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "WSH0702AWW/RBO": {"parent": "Climate Control", "sub": "Heaters"},
    "WSH3-1002-WHT": {"parent": "Climate Control", "sub": "Heaters"},

    # ── Laundry ──
    "BCED37": {"parent": "Major Appliances", "sub": "Laundry"},
    "BFLW27MW": {"parent": "Major Appliances", "sub": "Laundry"},
    "BPWH84W": {"parent": "Major Appliances", "sub": "Laundry"},
    "BPWM16W": {"parent": "Major Appliances", "sub": "Laundry"},
    "BWDS": {"parent": "Major Appliances", "sub": "Laundry"},
    "CASTER KIT": {"parent": "Major Appliances", "sub": "Laundry"},
    "DRYER LINT": {"parent": "Major Appliances", "sub": "Laundry"},
    "FW100-1388AS": {"parent": "Major Appliances", "sub": "Laundry"},
    "FW50-518A": {"parent": "Major Appliances", "sub": "Laundry"},
    "FW70-1558L": {"parent": "Major Appliances", "sub": "Laundry"},
    "GYJ60-88F1": {"parent": "Major Appliances", "sub": "Laundry"},
    
    # ── Massage Chairs ──
    "JL10003WL-KO": {"parent": "Major Appliances", "sub": "Massage Chairs"},
    "JL10003WL-WU": {"parent": "Major Appliances", "sub": "Massage Chairs"},
    "JL10003WL-YB": {"parent": "Major Appliances", "sub": "Massage Chairs"},

        # ── Refrigeration ──
    "BD100": {"parent": "Major Appliances", "sub": "Chest Freezers"},
    "UL-BD142-D": {"parent": "Major Appliances", "sub": "Chest Freezers"},
    "CCUK12W/ROA": {"parent": "Major Appliances", "sub": "Upright Freezers"},
    "CCUN28WV/ROA": {"parent": "Major Appliances", "sub": "Upright Freezers"},
    "BC 40": {"parent": "Major Appliances", "sub": "Refrigerators"},
    "BCRK17V": {"parent": "Major Appliances", "sub": "Refrigerators"},
    "NS-CF44BK3/NB": {"parent": "Major Appliances", "sub": "Refrigerators"},
    "RM3306W": {"parent": "Major Appliances", "sub": "Refrigerators"},
    "RM3316B": {"parent": "Major Appliances", "sub": "Refrigerators"},
    
    # ── Personal Care & Grooming ──
    "3043": {"parent": "Personal Care", "sub": "Scales"},
    "CBG1-5000-KIT": {"parent": "Personal Care", "sub": "Grooming"},
    "CBH1-4002-VTN": {"parent": "Personal Care", "sub": "Grooming"},
    "CBH1-4012-VTN": {"parent": "Personal Care", "sub": "Grooming"},
    "CPH1-9011-BOX": {"parent": "Personal Care", "sub": "Hair Styling"},
    "CXH1-5000-BOX": {"parent": "Personal Care", "sub": "Hair Styling"},
    "CXT1-4007-CMB": {"parent": "Personal Care", "sub": "Grooming"},
    "CBH1-4006-SIG": {"parent": "Personal Care", "sub": "Grooming"},
    "CBH1-4007-VTN": {"parent": "Personal Care", "sub": "Grooming"},
    "CBH1-4008-SIG": {"parent": "Personal Care", "sub": "Grooming"},
    "CBT1-3007-BLY": {"parent": "Personal Care", "sub": "Grooming"},
    "CBT1-6002-SLV": {"parent": "Personal Care", "sub": "Grooming"},
    "CBT1-7001-SIG": {"parent": "Personal Care", "sub": "Grooming"},
    "CXT1-3500-HYP": {"parent": "Personal Care", "sub": "Grooming"},
    "CXT1-6002-HYP": {"parent": "Personal Care", "sub": "Grooming"},
    "303DGNX": {"parent": "Personal Care", "sub": "Hair Styling"},
    "CBF1-2001-BLK": {"parent": "Personal Care", "sub": "Grooming"},
    "CBR1-1002-BLY": {"parent": "Personal Care", "sub": "Grooming"},
    "CBR1-1003-SIG": {"parent": "Personal Care", "sub": "Grooming"},
    "CBT1-9000-SIG": {"parent": "Personal Care", "sub": "Grooming"},
    "CXE1-2001-HYP": {"parent": "Personal Care", "sub": "Grooming"},
    "NV-09586": {"parent": "Personal Care", "sub": "Grooming"},
    "NV-09677": {"parent": "Personal Care", "sub": "Personal Care"},
    "VRD928982395": {"parent": "Personal Care", "sub": "Personal Care"},
    "CPH1-9010-BOX": {"parent": "Personal Care", "sub": "Hair Styling"},
    "CXH1-5003-BLK": {"parent": "Personal Care", "sub": "Hair Styling"},
    "RVDR5034N1": {"parent": "Personal Care", "sub": "Hair Styling"},
    "CXH1-6000-BLK": {"parent": "Personal Care", "sub": "Hair Styling"},
    "MG-1-BLK": {"parent": "Personal Care", "sub": "Massagers"},
    "MG-1-BLU": {"parent": "Personal Care", "sub": "Massagers"},
    "MG-1-CHR": {"parent": "Personal Care", "sub": "Massagers"},
    "MG-1-RED": {"parent": "Personal Care", "sub": "Massagers"},

    # ── Electronics, Audio & Accessories ──
    "S-15": {"parent": "Audio", "sub": "Stands"},
    "ST-2": {"parent": "Audio", "sub": "Stands"},
    "ST-200": {"parent": "Audio", "sub": "Stands"},
    "STA-10": {"parent": "Audio", "sub": "Stands"},
    "50HPBT500G": {"parent": "Audio", "sub": "Headphones"},
    "50HPBT500S": {"parent": "Audio", "sub": "Headphones"},
    "50TWS597G": {"parent": "Audio", "sub": "Earphones"},
    "A6CLUB-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "A6CLUB-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "ABX-1550S": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "ABX-160R": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "ABX-214R": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "ABX-82S": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BLW-HC101": {"parent": "Audio", "sub": "Headphones"},
    "BLWBT301": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BLWBT980B": {"parent": "Audio", "sub": "Earphones"},
    "BLWBT980W": {"parent": "Audio", "sub": "Earphones"},
    "BLWBT993": {"parent": "Audio", "sub": "Earphones"},
    "BT-1010-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1010-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1010-RED": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-111-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-111-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-111-RED": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-112-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-112-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-112-RED": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-16-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-17-FTB": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1934-GRN": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1953-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1956-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1956-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1956-RED": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1985-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-1985-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-2024-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-2024-SIL": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-2026": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-27": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-29-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-29-BRN": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-29-RED": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-35": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-402-Blk": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-64-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-70": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-8": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT300K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BTH655-W": {"parent": "Audio", "sub": "Earphones"},
    "BTH661-B": {"parent": "Audio", "sub": "Earphones"},
    "BTH661-BL": {"parent": "Audio", "sub": "Earphones"},
    "BTH661-W": {"parent": "Audio", "sub": "Earphones"},
    "BTH825-B": {"parent": "Audio", "sub": "Headphones"},
    "BTHP10": {"parent": "Audio", "sub": "Headphones"},
    "BTHP40": {"parent": "Audio", "sub": "Headphones"},
    "BTSB370": {"parent": "Audio", "sub": "Soundbars"},
    "BTSPK139": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BTSPK145": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BTSPK149": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BTSPK154": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BTSPK30B": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BTSPK62": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BTWS300": {"parent": "Audio", "sub": "Earphones"},
    "BTWSG20": {"parent": "Audio", "sub": "Earphones"},
    "BTWSPK20": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "CLP-10-YEL": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "E-1500": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "E-B5": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "E-B8": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "FBHP387S": {"parent": "Audio", "sub": "Headphones"},
    "FBHP546K": {"parent": "Audio", "sub": "Headphones"},
    "FBHP546R": {"parent": "Audio", "sub": "Headphones"},
    "FBHP546W": {"parent": "Audio", "sub": "Headphones"},
    "FBHP660K": {"parent": "Audio", "sub": "Headphones"},
    "FBX2202K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "FBX643K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "FBX647K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "FGHP245B": {"parent": "Audio", "sub": "Headphones"},
    "FSB228K-GT-DI": {"parent": "Audio", "sub": "Soundbars"},
    "FSB250K": {"parent": "Audio", "sub": "Soundbars"},
    "FTW388B": {"parent": "Audio", "sub": "Earphones"},
    "FTW626K": {"parent": "Audio", "sub": "Earphones"},
    "H-256BT-RED": {"parent": "Audio", "sub": "Headphones"},
    "HP-10-BLU": {"parent": "Audio", "sub": "Headphones"},
    "HP-10-SIL": {"parent": "Audio", "sub": "Headphones"},
    "HP-20-BLK": {"parent": "Audio", "sub": "Headphones"},
    "HP-E110": {"parent": "Audio", "sub": "Earphones"},
    "HP-E120-BLK": {"parent": "Audio", "sub": "Earphones"},
    "HP-E120-WHT": {"parent": "Audio", "sub": "Earphones"},
    "HP-E160BLK": {"parent": "Audio", "sub": "Headphones"},
    "HP-E160GRN": {"parent": "Audio", "sub": "Headphones"},
    "HP-E160SIL": {"parent": "Audio", "sub": "Headphones"},
    "HP-E60-BLK": {"parent": "Audio", "sub": "Headphones"},
    "HP-E60-DBL": {"parent": "Audio", "sub": "Headphones"},
    "HP-E60-RED": {"parent": "Audio", "sub": "Headphones"},
    "HP-E60-WHT": {"parent": "Audio", "sub": "Headphones"},
    "HPBT195K": {"parent": "Audio", "sub": "Headphones"},
    "HPSHM165": {"parent": "Audio", "sub": "Earphones"},
    "HPSHM224": {"parent": "Audio", "sub": "Earphones"},
    "HPSHM610TLZ": {"parent": "Audio", "sub": "Earphones"},
    "HPSHO224": {"parent": "Audio", "sub": "Earphones"},
    "HPSHO228": {"parent": "Audio", "sub": "Earphones"},
    "HPXBT105": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT180": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT301/BLWBT301": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT900B": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT910": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT911": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT957B": {"parent": "Audio", "sub": "Earphones"},
    "HPXBT957W": {"parent": "Audio", "sub": "Earphones"},
    "HPXBT960B": {"parent": "Audio", "sub": "Earphones"},
    "HPXBT960W": {"parent": "Audio", "sub": "Earphones"},
    "HPXBT969CR": {"parent": "Audio", "sub": "Earphones"},
    "HPXBT985": {"parent": "Audio", "sub": "Earphones"},
    "HPXBT999BK": {"parent": "Audio", "sub": "Earphones"},
    "HPXBTA010": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTA100": {"parent": "Audio", "sub": "Earphones"},
    "HPXBTA1000BK": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTA1000WH": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTA105": {"parent": "Audio", "sub": "Earphones"},
    "HPXBTA110": {"parent": "Audio", "sub": "Earphones"},
    "HPXBTA200": {"parent": "Audio", "sub": "Earphones"},
    "HPXBTAND": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTANDWH": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTCAT": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTDINO": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTO200": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTSP3": {"parent": "Audio", "sub": "Headphones"},
    "HPXBTSUN": {"parent": "Audio", "sub": "Headphones"},
    "HPXDLX100BK": {"parent": "Audio", "sub": "Headphones"},
    "HPXGX175": {"parent": "Audio", "sub": "Headphones"},
    "HPXGX275": {"parent": "Audio", "sub": "Headphones"},
    "HPXGX50": {"parent": "Audio", "sub": "Headphones"},
    "HPXGX85": {"parent": "Audio", "sub": "Headphones"},
    "HPXGXTW1": {"parent": "Audio", "sub": "Headphones"},
    "HPXHD200-WHT": {"parent": "Audio", "sub": "Earphones"},
    "HPXHM802": {"parent": "Audio", "sub": "Headphones"},
    "HPXHMCAT": {"parent": "Audio", "sub": "Headphones"},
    "HPXHMPRIN": {"parent": "Audio", "sub": "Headphones"},
    "HPXHO425": {"parent": "Audio", "sub": "Headphones"},
    "HPXHOKIDB": {"parent": "Audio", "sub": "Headphones"},
    "HPXHOKIDP": {"parent": "Audio", "sub": "Headphones"},
    "HPXHS861": {"parent": "Audio", "sub": "Headphones"},
    "HPXIC116": {"parent": "Audio", "sub": "Earphones"},
    "HPXIC150Z": {"parent": "Audio", "sub": "Earphones"},
    "HPXIC160": {"parent": "Audio", "sub": "Earphones"},
    "HPXICDLX": {"parent": "Audio", "sub": "Headphones"},
    "HPXSPBT6": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "HPXSPBT8": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "HPXSPBT9": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "HPXSPBTRGB": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "KP-500": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "LCS-150": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "M-6500-MKII": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MD565-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MD565-WHT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MPD3114": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MPX-1504": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MPX-1505": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MPX-8": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MPX-802": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MPX-803": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "MUZ40031W-BLK": {"parent": "Audio", "sub": "Earphones"},
    "NAS-3105D": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "P54-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-1001": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-1020": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-1501": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-151": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-151SM": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-2010": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-2015": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-2122": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-220W": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-288": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-311BT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-5190": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-68": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-806": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-840": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PSS1003M-BK": {"parent": "Audio", "sub": "Shelf Systems"},
    "RC-1932-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "RC-1932-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "RC-1932-RED": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "S100": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SBGHO425": {"parent": "Audio", "sub": "Headphones"},
    "SBHP550AK": {"parent": "Audio", "sub": "Earphones"},
    "SBT294K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SBT294NB": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SBX-1531": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SBX1036K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SBX1530K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SBX360K": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SC-2329BT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SNB-1100S": {"parent": "Audio", "sub": "Soundbars"},
    "SP-1700RBT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SP-2100RBT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SP-2120RBT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SP-2250RBT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SP-3115RBT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "SP-3210RBT": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "TWS150-WHT": {"parent": "Audio", "sub": "Earphones"},
    "TWS624NB": {"parent": "Audio", "sub": "Earphones"},
    "TWS624R": {"parent": "Audio", "sub": "Earphones"},
    "TWS624W": {"parent": "Audio", "sub": "Earphones"},
    "WH58-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WH58-GRN": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WH61-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WH61-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WH61-CMO": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WP63-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WP64-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WP64-GRY": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WPB2-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WPB2-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WPB220M-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WPBMINI-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WPBMINI-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WS10-BLU": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WS10-GRN": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WS10-PPL": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WS10-RED": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "XL-2120": {"parent": "Audio", "sub": "Bluetooth Speakers"},

    "BT-10BK": {"parent": "Audio", "sub": "Party Speakers"},
    "BT-10BL": {"parent": "Audio", "sub": "Party Speakers"},
    "BT-10R": {"parent": "Audio", "sub": "Party Speakers"},
    "BT-30": {"parent": "Audio", "sub": "Party Speakers"},
    "FBX1529ACSM": {"parent": "Audio", "sub": "Party Speakers"},
    "LMS-1234": {"parent": "Audio", "sub": "Party Speakers"},
    "LMS-210": {"parent": "Audio", "sub": "Party Speakers"},
    "LX-440": {"parent": "Audio", "sub": "Party Speakers"},
    "MPX-1505SM": {"parent": "Audio", "sub": "Party Speakers"},
    "MPX-24": {"parent": "Audio", "sub": "Party Speakers"},
    "NDS-8502": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-1203": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-1206": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-1206SM": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-1212": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-1213": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-1520": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-264": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-61089": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-831": {"parent": "Audio", "sub": "Party Speakers"},
    "PBX-BF12": {"parent": "Audio", "sub": "Party Speakers"},
    "SP-1217RBT": {"parent": "Audio", "sub": "Party Speakers"},
    "SP-1270RBT": {"parent": "Audio", "sub": "Party Speakers"},
    "SP-18RBT": {"parent": "Audio", "sub": "Party Speakers"},
    "SP-2080RBT": {"parent": "Audio", "sub": "Party Speakers"},
    "SP-212RBT": {"parent": "Audio", "sub": "Party Speakers"},
    "SP-2600RBT": {"parent": "Audio", "sub": "Party Speakers"},
    "SP-885RBT": {"parent": "Audio", "sub": "Party Speakers"},
    "SPX-2115R": {"parent": "Audio", "sub": "Party Speakers"},
    "TMS-101-BLK": {"parent": "Audio", "sub": "Party Speakers"},
    "WSC01-BLK": {"parent": "Audio", "sub": "Party Speakers"},
    "WSC01-BLU": {"parent": "Audio", "sub": "Party Speakers"},





    # ── Headphones ──
    "HPXBT-101B": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-101R": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-101W": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-202B": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-202R": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-202W": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-303B": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-303R": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-303W": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-404B": {"parent": "Audio", "sub": "Headphones"},
    "HPXBT-404W": {"parent": "Audio", "sub": "Headphones"},

    # Radio 
    "RCD5": {"parent": "Audio", "sub": "Radios"},
    "RETRO-10": {"parent": "Audio", "sub": "Radios"},
    "RETRO-12": {"parent": "Audio", "sub": "Radios"},
    "RX-3": {"parent": "Audio", "sub": "Radios"},
    "R-15BLK": {"parent": "Audio", "sub": "Radios"},
    "R-24": {"parent": "Audio", "sub": "Radios"},
    "R-42BT": {"parent": "Audio", "sub": "Radios"},
    "R-58-BLU": {"parent": "Audio", "sub": "Radios"},
    "R-58-IVY": {"parent": "Audio", "sub": "Radios"},
    "ER-7002-BL": {"parent": "Audio", "sub": "Radios"},
    "ER-7002-RD": {"parent": "Audio", "sub": "Radios"},
    "R-333BT-BLU": {"parent": "Audio", "sub": "Radios"},
    "R-333BT-RED": {"parent": "Audio", "sub": "Radios"},
    "R-334BT-BLK": {"parent": "Audio", "sub": "Radios"},
    "R-34": {"parent": "Audio", "sub": "Radios"},
    "RETRO-15": {"parent": "Audio", "sub": "Radios"},

    # ── Audio Players ──
    "CD-60R": {"parent": "Electronics", "sub": "CD Players"},
    "CV-103": {"parent": "Electronics", "sub": "Multimedia Players"},
    "DVD350H": {"parent": "Electronics", "sub": "DVD Players"},
    "MP-100": {"parent": "Electronics", "sub": "Multimedia Players"},
    "MP-200": {"parent": "Electronics", "sub": "Multimedia Players"},
    "PCD25": {"parent": "Electronics", "sub": "CD Players"},
    "PD-107/BLK": {"parent": "Electronics", "sub": "Multimedia Players"},
    "PD-109/BLK": {"parent": "Electronics", "sub": "Multimedia Players"},
    "PDT-307DTV": {"parent": "Electronics", "sub": "Multimedia Players"},
    "PDT-309DTV": {"parent": "Electronics", "sub": "Multimedia Players"},
    "PDT-312DTV": {"parent": "Electronics", "sub": "DVD Players"},
    "SC-25": {"parent": "Electronics", "sub": "DVD Players"},
    "VP-109/BLK": {"parent": "Electronics", "sub": "Multimedia Players"},
    "VP-110": {"parent": "Electronics", "sub": "DVD Players"},
    "NPB-426/BLK": {"parent": "Electronics", "sub": "CD Players"},
    "NPB-431": {"parent": "Electronics", "sub": "CD Players"},

    # ── Boomboxes & Bluetooth Speakers ──
    "BT-220": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-100": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-101": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-110": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-115": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-120": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-200": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-210": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-220": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-400": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-600": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PBX-800": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "BT-23": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "NAS-3082": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WA65-BLK": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "WA65-GRY": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "TMS-801-Red": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "TMS-801-Blu": {"parent": "Audio", "sub": "Bluetooth Speakers"},
    "PRCD667": {"parent": "Audio", "sub": "Boombox"},
    "PRCD685B": {"parent": "Audio", "sub": "Boombox"},
    "PRCDT588": {"parent": "Audio", "sub": "Boombox"},
    "PRCST100": {"parent": "Audio", "sub": "Boombox"},
    "EPB-3002": {"parent": "Audio", "sub": "Boombox"},
    "J-200BT": {"parent": "Audio", "sub": "Boombox"},
    "J-220BT": {"parent": "Audio", "sub": "Boombox"},
    "J-230BT-BLK": {"parent": "Audio", "sub": "Boombox"},
    "J-230BT-BLU": {"parent": "Audio", "sub": "Boombox"},
    "J-230BT-RED": {"parent": "Audio", "sub": "Boombox"},
    "J-250BT-BLK": {"parent": "Audio", "sub": "Boombox"},
    "J-250BT-SIL": {"parent": "Audio", "sub": "Boombox"},
    "J-290BT-BLK": {"parent": "Audio", "sub": "Boombox"},
    "J-290BT-SIL": {"parent": "Audio", "sub": "Boombox"},
    "LX-30": {"parent": "Audio", "sub": "Boombox"},
    "SCR-75-BLK": {"parent": "Audio", "sub": "Boombox"},

    # ── Microphones ──
    "M-310": {"parent": "Audio", "sub": "Microphones"},
    "M-336": {"parent": "Audio", "sub": "Microphones"},
    "M-551": {"parent": "Audio", "sub": "Microphones"},
    "M-552": {"parent": "Audio", "sub": "Microphones"},
    "M-600": {"parent": "Audio", "sub": "Microphones"},
    "MC101-BLK": {"parent": "Audio", "sub": "Microphones"},
    "MC101-BLU": {"parent": "Audio", "sub": "Microphones"},
    "MC101-PNK": {"parent": "Audio", "sub": "Microphones"},
    "MC101-RSG": {"parent": "Audio", "sub": "Microphones"},
    "MC101-SLV": {"parent": "Audio", "sub": "Microphones"},
    "MCX-804": {"parent": "Audio", "sub": "Microphones"},
    "MCX-852": {"parent": "Audio", "sub": "Microphones"},
    "MCX11B": {"parent": "Audio", "sub": "Microphones"},
    "MCX11BL": {"parent": "Audio", "sub": "Microphones"},
    "MCX11R": {"parent": "Audio", "sub": "Microphones"},
    "MCX20": {"parent": "Audio", "sub": "Microphones"},
    "MCX21": {"parent": "Audio", "sub": "Microphones"},
    "MCX30": {"parent": "Audio", "sub": "Microphones"},
    "MPH-20": {"parent": "Audio", "sub": "Microphones"},
    "NAM-980/BLK": {"parent": "Audio", "sub": "Microphones"},
    "NAM-984/BLK": {"parent": "Audio", "sub": "Microphones"},

    # Food Processors
    "FP-549W": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "FP-549BK": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "MG-400BK": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "MG-400W": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},

    # Dishwashers
    "BCD6W": {"parent": "Small Kitchen Appliances", "sub": "Dishwashers"},

    # Juicers
    "J-28BK": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    
        # ── Air Fryers & Toaster Ovens ──
    "AF-202BK": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "FT50931AMZ": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "AF-202W": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "AF-2400SI": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "AF-400DBK": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "AFWB7QWG13": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "CHTO40B": {"parent": "Small Kitchen Appliances", "sub": "Toaster Ovens"},
    "IM-436S": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "KE-OV-B101BK": {"parent": "Small Kitchen Appliances", "sub": "Toaster Ovens"},
    "TS-260W": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "TS-265": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "TS-280S": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "TS-284": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "R22997/RB": {"parent": "Small Kitchen Appliances", "sub": "Toaster Ovens"},
    "TS-260B": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "WTO1-1020-BLK": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "WTO1-1022-BLK": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "WTO1-1022-RED": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "WTO1-1022-WHT": {"parent": "Small Kitchen Appliances", "sub": "Toasters"},
    "TS-345B": {"parent": "Small Kitchen Appliances", "sub": "Toaster Ovens"},
    "MS33018213889/ROA": {"parent": "Small Kitchen Appliances", "sub": "Toaster Ovens"},
    "SM-AIR-1899/RBO": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "AF-800DBK": {"parent": "Small Kitchen Appliances", "sub": "Air Fryers"},
    "TS-345R": {"parent": "Small Kitchen Appliances", "sub": "Toaster Ovens"},
    "WTO1-1001-BLK": {"parent": "Small Kitchen Appliances", "sub": "Toaster Ovens"},

        # ── Kitchen Appliances ──
    "1945": {"parent": "Small Kitchen Appliances", "sub": "Pressure Cookers"},
    "1947": {"parent": "Small Kitchen Appliances", "sub": "Pressure Cookers"},
    "1949": {"parent": "Small Kitchen Appliances", "sub": "Pressure Cookers"},
    "BPC-112": {"parent": "Small Kitchen Appliances", "sub": "Pressure Cookers"},
    "SC-130S": {"parent": "Small Kitchen Appliances", "sub": "Slow Cookers"},
    "SC-135W": {"parent": "Small Kitchen Appliances", "sub": "Slow Cookers"},
    "SC-140BL": {"parent": "Small Kitchen Appliances", "sub": "Slow Cookers"},
    "SC-157S": {"parent": "Small Kitchen Appliances", "sub": "Slow Cookers"},
    "SM-SC-900": {"parent": "Small Kitchen Appliances", "sub": "Slow Cookers"},
    "J-30B": {"parent": "Small Kitchen Appliances", "sub": "Can Openers"},
    "J-30W": {"parent": "Small Kitchen Appliances", "sub": "Can Openers"},
    "MS81-020-100-52": {"parent": "Small Kitchen Appliances", "sub": "Kitchen Scales"},
    "SR-100": {"parent": "Small Kitchen Appliances", "sub": "Spice Racks"},
    "TS-1002": {"parent": "Small Kitchen Appliances", "sub": "Knife Sharpeners"},
    "J-15": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "J-26BK": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "ED-675G": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "ED-675R": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "ED-676BK": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "ED-676W": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "IM-409S": {"parent": "Small Kitchen Appliances", "sub": "Rice Cookers"},
    "RC-5110DS": {"parent": "Small Kitchen Appliances", "sub": "Rice Cookers"},
    "TS-15": {"parent": "Small Kitchen Appliances", "sub": "Rice Cookers"},
    "TS-380S": {"parent": "Small Kitchen Appliances", "sub": "Rice Cookers"},
    "TS-480S": {"parent": "Small Kitchen Appliances", "sub": "Rice Cookers"},
    "TS-700S": {"parent": "Small Kitchen Appliances", "sub": "Rice Cookers"},
    "BDK400B": {"parent": "Small Kitchen Appliances", "sub": "Cookware"},
    "DMO01001": {"parent": "Small Kitchen Appliances", "sub": "Grills"},
    "DMO01003": {"parent": "Small Kitchen Appliances", "sub": "Grills"},

    # ── Blenders & Mixers ──
    "HB-31W": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HB-32BK": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HB-33R": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "58148G": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "70450": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "BLSTBKP-BRO-000": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "BLSTMEGG0": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "BLSTTS-GTO-000": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "CE-BL029": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "CE-FP009": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "CH-1502": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "CH-1569": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "ED-160W": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "ED-250/R": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "ED-435/R": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "ED-770": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "FP-549W": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "FP-581": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "FP-585BK": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "GA-103S": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HB-32BK": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HB-33R": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HB-38BK": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "HB-38W": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "HM-44": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HM-48B": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HM-48R": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "HM-48W": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-191BK": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-191W": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-199": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-220B": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-220R": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-220W": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-920B": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-920R": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JB-920W": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JBS-1000BK": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "JBS-500BK": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "RJB-100BK": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "RJB-100W": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "SJ479": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "SM-1152": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "SM-1153": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "SM-1162BL": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "WBL1-1010-WHT": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "XJ14409": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "R50190-RBO": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "R53519/RB": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "R56202-RBO": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},
    "WBL1-1010-BLK": {"parent": "Small Kitchen Appliances", "sub": "Blenders & Mixers"},


    # ── Coffee & Tea ──
    "178": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "43680PS": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "80300PS": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "885": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CE-CM249": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CE-CM389": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CG-158B": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CG-158W": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CHCM12B": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "HE-760": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "IM-170S": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "KT-1618-B": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "KT-1780": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "KT-1900R": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "KT-1962BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1333": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1358-B": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1368": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1377-B": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1386-B": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1395": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1404": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-112B": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-113BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-119BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-119S": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-215W": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-219BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-219W": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "WCF1-1003-BWS": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "WTK1-1001-BLK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "KT-1610W": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "KT-1617-W": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "SM-KET-1386": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "176": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "177": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "179": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CG-158BL": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CG-162S": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "CTS-1000": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-1101BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-119R": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-212BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-215BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "TS-222BK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},
    "WCF1-1007-BLK": {"parent": "Small Kitchen Appliances", "sub": "Coffee & Tea"},

    # ── Heating & Cooking (Griddles, Microwaves, Pizza Makers) ──
    "AR-136": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "WGR1-1011-WHT": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "BC-2958CR": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "BDG-2200": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "CE23839": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "CHPM12R": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "CP43279": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "DF-730S": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "ED-302": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "ED-302-BUR": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "EM131A5C-BS": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "B20PXP78-A70W": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "GCST11N1WSS/ROA": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "HB8436127995-3/RB": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "MS8436193153-3/ROA": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "NN-SB65NS/ROA": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "NN-SC64MBC/RBO": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "NN-SN95HS/ROA": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "NN-SU64LW/RB": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "NNSU64LWC/RBO": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "NNSU65NBC/RBO": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "WSI-EM22AST/ROA": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "B20PXP78-A70B": {"parent": "Small Kitchen Appliances", "sub": "Microwaves"},
    "IM-306DB": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-124R": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-231S": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-240B": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-241BK": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-244BK": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-246": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-247BK": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-372": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-611SS": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-643BK": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-651": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-810": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-821": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-391": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "ED-587BK": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "ED-587W": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2600": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2601": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2605": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2606": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2680": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2681": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2685": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "SM-STV-2686": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-337": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-361BK": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-361W": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "TS-381": {"parent": "Small Kitchen Appliances", "sub": "Heating & Cooking"},
    "JC-1000": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "JC-452B": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "JC-452W": {"parent": "Small Kitchen Appliances", "sub": "Juicers"},
    "MC-109R": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "MC-109W": {"parent": "Small Kitchen Appliances", "sub": "Food Processors"},
    "SK-45": {"parent": "Small Kitchen Appliances", "sub": "Skillets"},
    "SK-46": {"parent": "Small Kitchen Appliances", "sub": "Skillets"},
    "SK-65": {"parent": "Small Kitchen Appliances", "sub": "Skillets"},
    "SK-67BK": {"parent": "Small Kitchen Appliances", "sub": "Skillets"},
    "SK-72BK": {"parent": "Small Kitchen Appliances", "sub": "Cookware"},
    "CCD100W6/ROA": {"parent": "Small Kitchen Appliances", "sub": "Dehydrators"},
    "GF-P1549-1042-RBO": {"parent": "Small Kitchen Appliances", "sub": "Kettles"},

    # ── Wine & Beverage Coolers ──
    "BC115SS9/NB": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},
    "NS-BC1ZSS9/NB": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},
    "BCC20W": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},
    "CK-CB14GRN": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},
    "CK-CB26GR": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},
    "BD60026": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},
    "FRWW4543AS/NB": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},
    "BD60316": {"parent": "Major Appliances", "sub": "Wine & Beverage Coolers"},

})